### ISSUE TITLE
New systems

### ISSUE THREAD

**Issue by mgoulartBR** [digitalLumberjack/retrobox-buildroot#10]
I was taking a looking for libretro cores and I think that it's possible to have more systems on RetroboxOS (maybe without installing new cores)

Without installing new cores:
- Sega 32x can be emulated using Picodrive LibretroCore(https://www.youtube.com/watch?v=z4qtFcEhjeA)
- Sega/Mega CD can be emulated using Picodrive or Genesis GX Plus LibretroCore
- Nintendo Famicom Disk System can be emulated using fceu-next LibretroCore

Installing new cores:
- 3DO (4DO LibretroCore)
- TurboGrafix-16 (Beetle/Mednafen PCE FAST LibretroCore)

**Comment by digitalLumberjack** [comment]
You're right.
I'm going to take a look at that.
TurboGraphx is already in the list (also called PCEngine)

**Comment by digitalLumberjack** [comment]
Ok so SegaCD runs ok, it will be in the next release.
Sega 32x is very slow on all games i tested, i will not add this system as i want only smooth emulators on the retrobox.
Fceum and fceu-next cores runs Family Disk System roms The same issue for both cores is it's impossible to change the disk side. So many games doesn't work. I posted an issue on both cores. We will se later if it is corrected. Let's take a look at nestopia core.

I'm also on the 4DO core.

**Comment by mgoulartBR** [comment]
Cool!

Maybe the Picodrive libcore don't have a better performance emulating 32x
compared with Picodrive "stand-alone".

On Wed, Jan 21, 2015 at 3:46 PM, digitalLumberjack <notifications@github.com

**Comment by digitalLumberjack** [comment]
In the next release, there will be SegaCD support and Family Computer Disk System support.
32x and 3do cannot run well on the raspberry for now.

I'll try later the standalone version of picodrive.

**Comment by mgoulartBR** [comment]
Awesome!!! Let's wait and see if 32x and 3DO will run better on future
releases!

**Comment by mgoulartBR** [comment]
I am exchanging some information about DOSBox, but it's necessary to know if it's possible to use joysticks (Bluetooth or USB) on it!
