### ISSUE TITLE
Making emulationstation launch automatically without .profile

### ISSUE THREAD

**Issue by jayminer81** [digitalLumberjack/retrobox-buildroot#5]
This is more of an idea than an issue, as things work now emulationstation is launched when root logs in and .profile get's executed. This makes it problematic to SSH to RetroboxOS because if emulationstation is already running the terminal just hangs directly after you entered the password. This can be solved by renaming .profile to something else, but this ends with you having to launch emulationstation manually each time you want to run it.

**Comment by digitalLumberjack** [comment]
fixed by  commit 2e312f23184febc9bc563ee788c25a5abfb399a6

The root password is "retroboxroot"
